services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HSEBL6XtcmW293VzjwdyJM
      MYSQL_DATABASE: items
      MYSQL_USER: user
      MYSQL_PASSWORD: wUsmbzq2puTYJSChA5ENvX
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "42001:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: HSEBL6XtcmW293VzjwdyJM
    ports:
      - "7654:80"